Added option to load custom ini (WIP)
antonioginer/switchres pull request #77
Opened 2020-12-21 23:13 UTC by alphanu1

Load a custom ini when using as a library (.so, .dll)

Sorry about the multiple commits.

2021-01-08 18:05 UTC, substring requested changes
Hi!

Glad to see you here, been watching over your work for years already :wink: Anyway we can get in touch on discord for example ?

For code stuff, see below

2021-01-08 18:05 UTC, substring commented on switchres_wrapper.cpp
> +}
Can you:
  * change the parameter to `const char*`
  * remove the forced `.ini` extension
  * remove that empty line

2021-01-08 19:26 UTC, alphanu1 commented
@substring Thanks for the nice welcome. Send me a invite to the channel please 😊

I have sorted these changes.

2021-01-08 19:42 UTC, substring commented
And forgot to ask you to squash your commits ;)

For the invitation : https://discord.gg/YtQ6pJh

2021-01-08 20:00 UTC, alphanu1 commented
@substring, no worries. Will do that shortly

2021-01-08 21:39 UTC, alphanu1 commented
@substring  all done.

2021-01-12 15:26 UTC, substring commented
Reading again, and forgive me as I should have mentioned this at first : the function needs to be in the srAPI struct (in both .h and .cpp).

2021-01-14 13:00 UTC, alphanu1 commented
@substring not really your fault. To be honest I should have noticed that. Should all be sorted now, hopefully  😊

2021-04-15 13:27 UTC, substring commented
So, I finally took the time to test this MR. In the current API state, it only works before `sr_init_disp()`, is that OK with you ?

2021-04-15 13:37 UTC, alphanu1 commented
Yeah, that should be fine.

2021-04-16 11:18 UTC, substring approved these changes

2021-04-16 11:27 UTC, merged